/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BallIndexRouteImport } from './routes/ball.index'
import { Route as BallRegisterRouteImport } from './routes/ball.register'
import { Route as ApiPublicFlutterwaveWebhookRouteImport } from './routes/api/public/flutterwave-webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BallIndexRoute = BallIndexRouteImport.update({
  id: '/ball/',
  path: '/ball/',
  getParentRoute: () => rootRouteImport,
} as any)
const BallRegisterRoute = BallRegisterRouteImport.update({
  id: '/ball/register',
  path: '/ball/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFlutterwaveWebhookRoute =
  ApiPublicFlutterwaveWebhookRouteImport.update({
    id: '/api/public/flutterwave-webhook',
    path: '/api/public/flutterwave-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ball/register': typeof BallRegisterRoute
  '/ball/': typeof BallIndexRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ball/register': typeof BallRegisterRoute
  '/ball': typeof BallIndexRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ball/register': typeof BallRegisterRoute
  '/ball/': typeof BallIndexRoute
  '/api/public/flutterwave-webhook': typeof ApiPublicFlutterwaveWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/ball/register' | '/ball/' | '/api/public/flutterwave-webhook'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/ball/register' | '/ball' | '/api/public/flutterwave-webhook'
  id:
    | '__root__'
    | '/'
    | '/ball/register'
    | '/ball/'
    | '/api/public/flutterwave-webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BallRegisterRoute: typeof BallRegisterRoute
  BallIndexRoute: typeof BallIndexRoute
  ApiPublicFlutterwaveWebhookRoute: typeof ApiPublicFlutterwaveWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ball/': {
      id: '/ball/'
      path: '/ball'
      fullPath: '/ball/'
      preLoaderRoute: typeof BallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ball/register': {
      id: '/ball/register'
      path: '/ball/register'
      fullPath: '/ball/register'
      preLoaderRoute: typeof BallRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/flutterwave-webhook': {
      id: '/api/public/flutterwave-webhook'
      path: '/api/public/flutterwave-webhook'
      fullPath: '/api/public/flutterwave-webhook'
      preLoaderRoute: typeof ApiPublicFlutterwaveWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BallRegisterRoute: BallRegisterRoute,
  BallIndexRoute: BallIndexRoute,
  ApiPublicFlutterwaveWebhookRoute: ApiPublicFlutterwaveWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
