// Country list with international dialling codes. Nigeria first only because most of the community is there.
export type Country = { name: string; code: string; dial: string };

export const COUNTRIES: Country[] = [
  { name: "Nigeria", code: "NG", dial: "+234" },
  { name: "Algeria", code: "DZ", dial: "+213" },
  { name: "Benin", code: "BJ", dial: "+229" },
  { name: "Botswana", code: "BW", dial: "+267" },
  { name: "Burkina Faso", code: "BF", dial: "+226" },
  { name: "Cameroon", code: "CM", dial: "+237" },
  { name: "Chad", code: "TD", dial: "+235" },
  { name: "Côte d'Ivoire", code: "CI", dial: "+225" },
  { name: "Egypt", code: "EG", dial: "+20" },
  { name: "Ethiopia", code: "ET", dial: "+251" },
  { name: "Gambia", code: "GM", dial: "+220" },
  { name: "Ghana", code: "GH", dial: "+233" },
  { name: "Guinea", code: "GN", dial: "+224" },
  { name: "Kenya", code: "KE", dial: "+254" },
  { name: "Liberia", code: "LR", dial: "+231" },
  { name: "Libya", code: "LY", dial: "+218" },
  { name: "Mali", code: "ML", dial: "+223" },
  { name: "Mauritania", code: "MR", dial: "+222" },
  { name: "Morocco", code: "MA", dial: "+212" },
  { name: "Niger", code: "NE", dial: "+227" },
  { name: "Rwanda", code: "RW", dial: "+250" },
  { name: "Senegal", code: "SN", dial: "+221" },
  { name: "Sierra Leone", code: "SL", dial: "+232" },
  { name: "Somalia", code: "SO", dial: "+252" },
  { name: "South Africa", code: "ZA", dial: "+27" },
  { name: "Sudan", code: "SD", dial: "+249" },
  { name: "Tanzania", code: "TZ", dial: "+255" },
  { name: "Togo", code: "TG", dial: "+228" },
  { name: "Tunisia", code: "TN", dial: "+216" },
  { name: "Uganda", code: "UG", dial: "+256" },
  { name: "Zambia", code: "ZM", dial: "+260" },
  { name: "Zimbabwe", code: "ZW", dial: "+263" },
  { name: "Australia", code: "AU", dial: "+61" },
  { name: "Bahrain", code: "BH", dial: "+973" },
  { name: "Bangladesh", code: "BD", dial: "+880" },
  { name: "Canada", code: "CA", dial: "+1" },
  { name: "France", code: "FR", dial: "+33" },
  { name: "Germany", code: "DE", dial: "+49" },
  { name: "India", code: "IN", dial: "+91" },
  { name: "Indonesia", code: "ID", dial: "+62" },
  { name: "Ireland", code: "IE", dial: "+353" },
  { name: "Jordan", code: "JO", dial: "+962" },
  { name: "Kuwait", code: "KW", dial: "+965" },
  { name: "Malaysia", code: "MY", dial: "+60" },
  { name: "Netherlands", code: "NL", dial: "+31" },
  { name: "Oman", code: "OM", dial: "+968" },
  { name: "Pakistan", code: "PK", dial: "+92" },
  { name: "Qatar", code: "QA", dial: "+974" },
  { name: "Saudi Arabia", code: "SA", dial: "+966" },
  { name: "Turkey", code: "TR", dial: "+90" },
  { name: "United Arab Emirates", code: "AE", dial: "+971" },
  { name: "United Kingdom", code: "GB", dial: "+44" },
  { name: "United States", code: "US", dial: "+1" },
];

export const INTERESTS = [
  "Cybersecurity", "Software Engineering", "Product", "Design", "AI", "Data", "Digital Forensics",
  "Technology Law", "Entrepreneurship", "Leadership", "Community", "Career Growth", "Content Creation",
  "Research", "Education",
];
